on:
  push:
    branches: [master]
jobs:
  k6_perfomance_test:
    name: k6 test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: test/check.js